version: '3'
services:
  nginx1:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - mynet

  nginx2:
    image: nginx
    ports:
      - "8081:80"
    networks:
      - mynet

  centos-container:
    image: centos:latest
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - mynet

networks:
  mynet:
    driver: bridge