FROM registry.access.redhat.com/ubi8/ubi:8.1
# Update system and install required packages
# Set maintainer information (optional)
LABEL maintainer="vibish@gmail.com"
RUN yum update -y && \
    yum install -y iputils bind-utils procps-ng net-tools git wget openssh-server.x86_64 && \
    yum clean all
RUN mkdir -p /var/run/sshd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile
RUN echo 'root:vibishnathan' |chpasswd
RUN ssh-keygen -A 
EXPOSE 22
CMD [ "/usr/sbin/sshd", "-D"]